```python
# appname/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


class UserManager(BaseUserManager):
    """Manager for users."""
  
    def create_user(self, email, password=None, **extra_fields):
        """Create, save and return a new user"""
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
  
        return user

class User(AbstractBaseUser, PermissionsMixin):
    """User in the system"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    
    objects = UserManager()
    
    USERNAME_FIELD = 'email'

## settings.py
AUTH_USER_MODEL = 'core.User'
```

```bash
docker-compose run app sh -c "python manage.py makemigrations"

$ docker-composer run --rm app sh -c "python manage.py wait_for_db && python m
anage.py migrate"
bash: docker-composer: command not found

Wook@DESKTOP-LAGUL92 MINGW64 ~/Desktop/buildapi/api-prac (master)
$ docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py migrate"
[+] Running 1/0
 - Container api-prac-db-1  Running                                      0.0s 
Waitng for database ...
Database available !
Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/py/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/py/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/py/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/py/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/py/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "/py/lib/python3.9/site-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency core.0001_initial on database 'default'.


$ docker volume ls
DRIVER    VOLUME NAME
local     76ce5b60e9957a50f41403dbb74099fa139750fb8c4b44f84706e4dc84f6d2d3    
local     763a39fe8748532bd603e9b43ed2db101d33b5341d0f4e4ed17336d2496e49d5    
local     api-prac_dev-db-data
local     cb612778c9f6ed1379f8c71f8bc758d6d1af9ad278420e971a227990bfffaab5    
local     f9a4b5317ba0c0c7da3145d4e097636b6b9982105fdaa0b920cc1fe8ba0d9967 

$ docker volume rm api-prac_dev-db-data
Error response from daemon: remove api-prac_dev-db-data: volume is in use - [d4b17c3b93538e3894d7ca940be2ab9e19797c5a4076693fea45362e9e3ceb48]

$ docker-compose down
[+] Running 3/3
 - Container api-prac-app-1  Removed                                     0.0s 
 - Container api-prac-db-1   Removed                                     0.3s 
 - Network api-prac_default  Removed                                     0.2s

$ docker volume rm api-prac_dev-db-data
api-prac_dev-db-data

$ docker volume ls
DRIVER    VOLUME NAME
local     76ce5b60e9957a50f41403dbb74099fa139750fb8c4b44f84706e4dc84f6d2d3    
local     763a39fe8748532bd603e9b43ed2db101d33b5341d0f4e4ed17336d2496e49d5    
local     cb612778c9f6ed1379f8c71f8bc758d6d1af9ad278420e971a227990bfffaab5    
local     f9a4b5317ba0c0c7da3145d4e097636b6b9982105fdaa0b920cc1fe8ba0d9967    

$ docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py migrate"
[+] Running 3/0
 - Network api-prac_default       Created                                0.0s 
 - Volume "api-prac_dev-db-data"  Cre...                                 0.0s 
 - Container api-prac-db-1        Created                                0.0s 
[+] Running 1/1
 - Container api-prac-db-1  Started                                      0.3s 
Waitng for database ...
Database available !
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying core.0001_initial... OK ##
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying sessions.0001_initial... OK
```