```python
"""
Test for models.
"""

from django.test import TestCase
from django.contrib.auth import get_user_model
  
class ModelTests(TestCase):
    """Test models"""

    def test_create_user_with_email_successful(self):
        email = 'test@example.com'
        password = 'testpass123'
        user = get_user_model().objects.create_user(
            email=email,
            password=password,
        )

        self.assertEqual(user.email, email)
        self.assertTrue(user.check_password(password))


    def test_new_user_email_normalized(self):
        """Test email is normalized for new users."""
        sample_emails = [
            ['test1@EXAMPLE.com', 'test1@example.com'],
            ['Test2@Example.com', 'Test2@example.com'],
            ['TEST3@EAXMPLE.COM', 'TEST3@example.com'],
            ['test4@example.COM', 'test4@example.com'],
        ]

        for email, expected in sample_emails:
            user = get_user_model().objects.create_user(email, 'sample123')
            self.assertEqual(user.email, expected)
```

```bash

$ docker-compose run --rm app sh -c "python manage.py test"
[+] Running 1/0
 - Container api-prac-db-1  Running                                      0.0s 
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.F..Waitng for database ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database unvailable, waiting 1 second ...
Database available !
.Waitng for database ...
Database available !
.
======================================================================        
FAIL: test_new_user_email_normalized (core.tests.test_models.ModelTests)      
Test email is normalized for new users.
----------------------------------------------------------------------        
Traceback (most recent call last):
  File "/app/core/tests/test_models.py", line 32, in test_new_user_email_normalized
    self.assertEqual(user.email, expected)
AssertionError: 'test1@EXAMPLE.com' != 'test1@example.com'
- test1@EXAMPLE.com
+ test1@example.com


----------------------------------------------------------------------        
Ran 6 tests in 0.241s

FAILED (failures=1)
Destroying test database for alias 'default'...
```
[self.normalize_email](https://dev-mht.tistory.com/163)
